/** 互動作品 slug（與 `workCurveBySlug`、`WorkInteractiveStage` 同步） */
export const workInteractiveSlugs = [
  'rose-curve',
  'lissajous-curve',
  'harmonograph-curve',
  'spirograph-curve',
  'standing-wave',
  'interference-fringes',
  'chladni-figures',
  'parabolic-reflection',
  'conic-envelope',
  'conic-focus-locus',
  'linear-transform-grid',
  'affine-transform-pattern',
  'rotation-scale-composition',
  'affine-ifs-fractal',
  'riemann-sum',
  'tangent-approximation',
  'catenary',
  'equiangular-spiral',
  'vector-field-patterns',
  'vector-field-streamlines',
  'vector-addition-scalar',
  'dot-product-geometry',
  'law-of-sines-cosines',
  'unit-circle-trig-definition',
  'trig-angle-identities',
  'vector-projection',
  'complex-arithmetic-geometry',
  'complex-polar-form',
  'euler-formula-rotation',
  'julia-set',
  'complex-phase-portrait',
  'arithmetic-geometric-sequences',
  'fibonacci-spiral',
  'sierpinski-triangle',
  'basel-problem',
  'logistic-bifurcation',
  'pascals-triangle',
  'combinatorial-path-counting',
  'binomial-expansion-geometry',
  'catalan-numbers',
  'conditional-probability-bayes',
  'binomial-to-normal',
  'buffon-needle',
  'exponential-growth-decay',
  'logarithmic-scale',
  'natural-log-e-geometry',
  'logistic-curve',
  'function-graph-transform',
  'quadratic-completing-square',
  'polynomial-roots-multiplicity',
  'inverse-function-reflection',
  'eigenvector-geometry',
  'function-derivative-graph',
  'taylor-polynomial-approximation',
] as const;

export type WorkInteractiveSlug = (typeof workInteractiveSlugs)[number];
export type WorkInteractionHint = 'button' | 'input' | 'select' | 'none';

export const workInteractionHints = {
  'rose-curve': 'input',
  'lissajous-curve': 'input',
  'harmonograph-curve': 'input',
  'spirograph-curve': 'input',
  'standing-wave': 'input',
  'interference-fringes': 'input',
  'chladni-figures': 'input',
  'parabolic-reflection': 'input',
  'conic-envelope': 'input',
  'conic-focus-locus': 'input',
  'linear-transform-grid': 'input',
  'affine-transform-pattern': 'input',
  'rotation-scale-composition': 'input',
  'affine-ifs-fractal': 'input',
  'riemann-sum': 'input',
  'tangent-approximation': 'input',
  'catenary': 'input',
  'equiangular-spiral': 'input',
  'vector-field-patterns': 'button',
  'vector-field-streamlines': 'input',
  'vector-addition-scalar': 'button',
  'dot-product-geometry': 'button',
  'law-of-sines-cosines': 'button',
  'unit-circle-trig-definition': 'button',
  'trig-angle-identities': 'button',
  'vector-projection': 'button',
  'complex-arithmetic-geometry': 'input',
  'complex-polar-form': 'input',
  'euler-formula-rotation': 'input',
  'julia-set': 'button',
  'complex-phase-portrait': 'input',
  'arithmetic-geometric-sequences': 'button',
  'fibonacci-spiral': 'input',
  'sierpinski-triangle': 'button',
  'basel-problem': 'button',
  'logistic-bifurcation': 'button',
  'pascals-triangle': 'button',
  'combinatorial-path-counting': 'button',
  'binomial-expansion-geometry': 'button',
  'catalan-numbers': 'button',
  'conditional-probability-bayes': 'button',
  'binomial-to-normal': 'button',
  'buffon-needle': 'button',
  'exponential-growth-decay': 'button',
  'logarithmic-scale': 'button',
  'natural-log-e-geometry': 'button',
  'logistic-curve': 'button',
  'function-graph-transform': 'input',
  'quadratic-completing-square': 'input',
  'polynomial-roots-multiplicity': 'input',
  'inverse-function-reflection': 'input',
  'eigenvector-geometry': 'input',
  'function-derivative-graph': 'input',
  'taylor-polynomial-approximation': 'input',
} satisfies Record<WorkInteractiveSlug, WorkInteractionHint>;

export function isWorkInteractive(slug: string): slug is WorkInteractiveSlug {
  return (workInteractiveSlugs as readonly string[]).includes(slug);
}

export function workControlsMountId(slug: WorkInteractiveSlug): string {
  return `${slug}-controls`;
}
